server:
  port: 8083

spring:
  application:
    name: notification-service
  
  # Database configuration
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/stocktracker}
    username: ${DATABASE_USERNAME:stocktracker}
    password: ${DATABASE_PASSWORD:password}
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-timeout: 20000
      idle-timeout: 300000
      max-lifetime: 1200000
      maximum-pool-size: 10
      minimum-idle: 5
      pool-name: NotificationCP

  # JPA configuration
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  # Email configuration
  mail:
    host: ${SMTP_HOST:smtp.gmail.com}
    port: ${SMTP_PORT:587}
    username: ${SMTP_USERNAME:}
    password: ${SMTP_PASSWORD:}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          timeout: 20000
          connectiontimeout: 20000
          writetimeout: 20000

  # Kafka configuration
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    consumer:
      group-id: notification-service
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      enable-auto-commit: false

  # Redis configuration
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:}
      database: 2
      timeout: 2000ms

  # Async configuration
  task:
    execution:
      pool:
        core-size: 5
        max-size: 20
        queue-capacity: 100
        keep-alive: 60s
      thread-name-prefix: notification-async-

# Application configuration
app:
  kafka:
    topics:
      stock-alerts: ${KAFKA_TOPIC_STOCK_ALERTS:stock-alerts}
      price-alerts: ${KAFKA_TOPIC_PRICE_ALERTS:price-alerts}
      news-alerts: ${KAFKA_TOPIC_NEWS_ALERTS:news-alerts}
      volume-alerts: ${KAFKA_TOPIC_VOLUME_ALERTS:volume-alerts}

  mail:
    from: ${MAIL_FROM:noreply@stocktracker.com}
    company-name: ${COMPANY_NAME:StockTracker}
    
  sms:
    provider: twilio
    twilio:
      account-sid: ${TWILIO_ACCOUNT_SID:}
      auth-token: ${TWILIO_AUTH_TOKEN:}
      from-number: ${TWILIO_FROM_NUMBER:}
  
  push:
    firebase:
      service-account-key: ${FIREBASE_SERVICE_ACCOUNT_KEY:}
      project-id: ${FIREBASE_PROJECT_ID:}

  notification:
    retry:
      max-attempts: 3
      initial-delay: 60000 # 1 minute
      multiplier: 2
      max-delay: 600000 # 10 minutes
    
    cleanup:
      retention-days: 30
      batch-size: 1000

# Circuit breaker configuration
resilience4j:
  circuitbreaker:
    instances:
      email-service:
        register-health-indicator: true
        ring-buffer-size-in-closed-state: 10
        ring-buffer-size-in-half-open-state: 3
        wait-duration-in-open-state: 30s
        failure-rate-threshold: 50
      
      sms-service:
        register-health-indicator: true
        ring-buffer-size-in-closed-state: 10
        ring-buffer-size-in-half-open-state: 3
        wait-duration-in-open-state: 30s
        failure-rate-threshold: 50

# Actuator configuration
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus,kafka
  endpoint:
    health:
      show-details: always
      show-components: always
  metrics:
    export:
      prometheus:
        enabled: true
    distribution:
      percentiles-histogram:
        http.server.requests: true

# Health checks
  health:
    kafka:
      enabled: true
    redis:
      enabled: true
    db:
      enabled: true
    mail:
      enabled: true

# Logging configuration
logging:
  level:
    com.stocktracker.notification: DEBUG
    org.springframework.kafka: INFO
    org.springframework.mail: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: logs/notification-service.log
    max-size: 100MB
    max-history: 30